// Human readable names for level numbers, level script commands and surface types,
// matching the definitions in the SM64 decompilation (levels/level_defines.h,
// include/level_commands.h and include/surface_terrain.h).

export const LEVEL_NAMES = {
  4: 'Big Boo\'s Haunt (BBH)',
  5: 'Cool, Cool Mountain (CCM)',
  6: 'Castle Inside',
  7: 'Hazy Maze Cave (HMC)',
  8: 'Shifting Sand Land (SSL)',
  9: 'Bob-omb Battlefield (BOB)',
  10: 'Snowman\'s Land (SL)',
  11: 'Wet-Dry World (WDW)',
  12: 'Jolly Roger Bay (JRB)',
  13: 'Tiny-Huge Island (THI)',
  14: 'Tick Tock Clock (TTC)',
  15: 'Rainbow Ride (RR)',
  16: 'Castle Grounds',
  17: 'Bowser in the Dark World (BITDW)',
  18: 'Vanish Cap under the Moat (VCUTM)',
  19: 'Bowser in the Fire Sea (BITFS)',
  20: 'Secret Aquarium (SA)',
  21: 'Bowser in the Sky (BITS)',
  22: 'Lethal Lava Land (LLL)',
  23: 'Dire, Dire Docks (DDD)',
  24: 'Whomp\'s Fortress (WF)',
  25: 'Ending',
  26: 'Castle Courtyard',
  27: 'Peach\'s Secret Slide (PSS)',
  28: 'Cavern of the Metal Cap (COTMC)',
  29: 'Tower of the Wing Cap (TOTWC)',
  30: 'Bowser 1 Arena',
  31: 'Wing Mario over the Rainbow (WMOTR)',
  33: 'Bowser 2 Arena',
  34: 'Bowser 3 Arena',
  36: 'Tall, Tall Mountain (TTM)',
};

export const LEVEL_COMMANDS = {
  0x00: 'EXECUTE',
  0x01: 'EXIT_AND_EXECUTE',
  0x02: 'EXIT',
  0x03: 'SLEEP',
  0x04: 'SLEEP_BEFORE_EXIT',
  0x05: 'JUMP',
  0x06: 'JUMP_LINK',
  0x07: 'RETURN',
  0x08: 'JUMP_LINK_PUSH_ARG',
  0x09: 'JUMP_N_TIMES',
  0x0a: 'LOOP_BEGIN',
  0x0b: 'LOOP_UNTIL',
  0x0c: 'JUMP_IF',
  0x0d: 'JUMP_LINK_IF',
  0x0e: 'SKIP_IF',
  0x0f: 'SKIP',
  0x10: 'SKIP_NOP',
  0x11: 'CALL',
  0x12: 'CALL_LOOP',
  0x13: 'SET_REG',
  0x14: 'PUSH_POOL',
  0x15: 'POP_POOL',
  0x16: 'FIXED_LOAD',
  0x17: 'LOAD_RAW',
  0x18: 'LOAD_MIO0/LOAD_YAY0',
  0x19: 'LOAD_MARIO_HEAD',
  0x1a: 'LOAD_MIO0_TEXTURE/LOAD_YAY0_TEXTURE',
  0x1b: 'INIT_LEVEL',
  0x1c: 'CLEAR_LEVEL',
  0x1d: 'ALLOC_LEVEL_POOL',
  0x1e: 'FREE_LEVEL_POOL',
  0x1f: 'AREA',
  0x20: 'END_AREA',
  0x21: 'LOAD_MODEL_FROM_DL',
  0x22: 'LOAD_MODEL_FROM_GEO',
  0x23: 'CMD23',
  0x24: 'OBJECT_WITH_ACTS',
  0x25: 'MARIO',
  0x26: 'WARP_NODE',
  0x27: 'PAINTING_WARP_NODE',
  0x28: 'INSTANT_WARP',
  0x29: 'LOAD_AREA',
  0x2a: 'UNLOAD_AREA',
  0x2b: 'MARIO_POS',
  0x2c: 'UNLOAD_MARIO_AREA',
  0x2d: 'UPDATE_OBJECTS',
  0x2e: 'TERRAIN',
  0x2f: 'ROOMS',
  0x30: 'SHOW_DIALOG',
  0x31: 'TERRAIN_TYPE',
  0x32: 'NOP',
  0x33: 'TRANSITION',
  0x34: 'BLACKOUT',
  0x35: 'GAMMA',
  0x36: 'SET_BACKGROUND_MUSIC',
  0x37: 'SET_MENU_MUSIC',
  0x38: 'STOP_MUSIC',
  0x39: 'MACRO_OBJECTS',
  0x3a: 'CMD3A',
  0x3b: 'WHIRLPOOL',
  0x3c: 'GET_OR_SET',
};

export const SURFACE_TYPES = {
  0x00: 'SURFACE_DEFAULT',
  0x01: 'SURFACE_BURNING',
  0x04: 'SURFACE_0004',
  0x05: 'SURFACE_HANGABLE',
  0x09: 'SURFACE_SLOW',
  0x0a: 'SURFACE_DEATH_PLANE',
  0x0b: 'SURFACE_CLOSE_CAMERA',
  0x0d: 'SURFACE_WATER',
  0x0e: 'SURFACE_FLOWING_WATER',
  0x12: 'SURFACE_INTANGIBLE',
  0x13: 'SURFACE_VERY_SLIPPERY',
  0x14: 'SURFACE_SLIPPERY',
  0x15: 'SURFACE_NOT_SLIPPERY',
  0x16: 'SURFACE_TTM_VINES',
  0x1a: 'SURFACE_MGR_MUSIC',
  0x1b: 'SURFACE_INSTANT_WARP_1B',
  0x1c: 'SURFACE_INSTANT_WARP_1C',
  0x1d: 'SURFACE_INSTANT_WARP_1D',
  0x1e: 'SURFACE_INSTANT_WARP_1E',
  0x21: 'SURFACE_SHALLOW_QUICKSAND',
  0x22: 'SURFACE_DEEP_QUICKSAND',
  0x23: 'SURFACE_INSTANT_QUICKSAND',
  0x24: 'SURFACE_DEEP_MOVING_QUICKSAND',
  0x25: 'SURFACE_SHALLOW_MOVING_QUICKSAND',
  0x26: 'SURFACE_QUICKSAND',
  0x27: 'SURFACE_MOVING_QUICKSAND',
  0x28: 'SURFACE_WALL_MISC',
  0x29: 'SURFACE_NOISE_DEFAULT',
  0x2a: 'SURFACE_NOISE_SLIPPERY',
  0x2c: 'SURFACE_HORIZONTAL_WIND',
  0x2d: 'SURFACE_INSTANT_MOVING_QUICKSAND',
  0x2e: 'SURFACE_ICE',
  0x2f: 'SURFACE_LOOK_UP_WARP',
  0x30: 'SURFACE_HARD',
  0x32: 'SURFACE_WARP',
  0x33: 'SURFACE_TIMER_START',
  0x34: 'SURFACE_TIMER_END',
  0x35: 'SURFACE_HARD_SLIPPERY',
  0x36: 'SURFACE_HARD_VERY_SLIPPERY',
  0x37: 'SURFACE_HARD_NOT_SLIPPERY',
  0x38: 'SURFACE_VERTICAL_WIND',
  0x65: 'SURFACE_BOSS_FIGHT_CAMERA',
  0x66: 'SURFACE_CAMERA_FREE_ROAM',
  0x68: 'SURFACE_THI3_WALLKICK',
  0x69: 'SURFACE_CAMERA_PLATFORM',
  0x6e: 'SURFACE_CAMERA_MIDDLE',
  0x6f: 'SURFACE_CAMERA_ROTATE_RIGHT',
  0x70: 'SURFACE_CAMERA_ROTATE_LEFT',
  0x72: 'SURFACE_CAMERA_BOUNDARY',
  0x73: 'SURFACE_NOISE_VERY_SLIPPERY_73',
  0x74: 'SURFACE_NOISE_VERY_SLIPPERY_74',
  0x75: 'SURFACE_NOISE_VERY_SLIPPERY',
  0x76: 'SURFACE_NO_CAM_COLLISION',
  0x77: 'SURFACE_NO_CAM_COLLISION_77',
  0x78: 'SURFACE_NO_CAM_COL_VERY_SLIPPERY',
  0x79: 'SURFACE_NO_CAM_COL_SLIPPERY',
  0x7a: 'SURFACE_SWITCH',
  0x7b: 'SURFACE_VANISH_CAP_WALLS',
};

export function levelName(id) {
  return LEVEL_NAMES[id] ?? `Level ${id}`;
}

export function surfaceTypeName(type) {
  return SURFACE_TYPES[type] ?? `SURFACE_${type.toString(16).toUpperCase().padStart(4, '0')}`;
}
